" vimrc - 2025-01-27 - jwh
" vim config - converted from neovim init.vim to use XDG paths
" Based on init.vim from 2024-05-06

" plug.vim install and run
" Download plug.vim if it doesn't exist yet
" Using XDG_CONFIG_HOME paths
let data_dir = exists('$XDG_CONFIG_HOME') ? expand('$XDG_CONFIG_HOME') . '/vim' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" Always use the system clipboard (requires vim compiled with +clipboard)
if has('clipboard')
  set clipboard^=unnamed,unnamedplus
endif

set nocompatible

" defaults - these are mostly for vim since neovim has them by default
if has('autocmd')
  filetype plugin indent on
endif

if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

set autoindent
set autoread
set backspace=indent,eol,start
set complete-=i
set display=lastline
set encoding=utf-8
set formatoptions=tcqj
set history=10000
set hlsearch                    " highlight searched phrases
set incsearch                   " highlight as you type
set langnoremap
set laststatus=2                " always show the status bar on the last window
" show tabs as "▸·", end-of-line as "↲", and trailing spaces as "·"
set listchars=tab:▸·,trail:·,eol:↲,nbsp:␣
set list
set magic
if has('mouse')
  set mouse=a
endif
set modelines=5                 " number of lines to check for modeline
set nrformats=hex,bin           " what number formats to consider when using C-A C-X
set sessionoptions-=options     " for :mksession command
set smarttab
set tabpagemax=50
set tags=./tags;,tags
set ttyfast
set viminfo+=!
set wildmenu                    " broader command line completion

" Load matchit.vim, if a newer version isn't already installed.
if !exists("g:loaded_matchit") && findfile("plugin/matchit.vim", &runtimepath) ==# ""
  runtime! macros/matchit.vim
endif

"
" start my options
set hidden                      " abandon hidden buffers

" save undo-trees in files (using XDG paths)
if has('persistent_undo')
  set undofile
  let &undodir = expand(data_dir) . '/undo'
  if !isdirectory(&undodir)
    call mkdir(&undodir, "p", 0700)
  endif
  set undolevels=10000
  set undoreload=10000
endif

" seems to cause issue with abbrv starting with _
"set iskeyword-=_                " treat '_' as word separator

" UI
set report=0                    " always report # of lines changed for command
set ruler
set scrolloff=1
set sidescroll=3
set splitbelow
set splitright
set showmode
set showmatch                   " show matching brackets
set showcmd

" LINE NUMBERING
set number
"set relativenumber

" number when in insert or focus is lost. relative in command mode
" could instead use Plug 'jeffkreeftmeijer/vim-numbertoggle'
if exists('+relativenumber')
  augroup numbertoggle
    autocmd!
    autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
    autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
  augroup END
endif

" INDENTATION
set smartindent
set softtabstop=4
set shiftwidth=4
set tabstop=4
set shiftround                  " round indent to multiple of shiftwidth
set copyindent
set expandtab
set cindent

autocmd FileType c setlocal noet ts=8 sw=8 tw=80
autocmd FileType go setlocal noet ts=4 sw=4
autocmd FileType html setlocal et ts=2 sw=2
autocmd FileType markdown setlocal et ts=2 sw=2 tw=80
autocmd FileType python setlocal et ts=4 sw=4

" MARKDOWN FOLDING
"let g:markdown_folding = 1

" VIM-PLUG (using XDG paths)
let plug_dir = expand(data_dir) . '/plugged'
call plug#begin(plug_dir)
Plug 'wellle/context.vim'
Plug 'sheerun/vim-polyglot'
Plug 'jeffkreeftmeijer/vim-dim'
Plug 'jkramer/vim-checkbox'
Plug 'dracula/vim', { 'as': 'dracula' }
call plug#end()

" colorscheme nord
" in theory dim allows the terminals colors to work
" use colorscheme grim for greyscale

" colorscheme dim
colorscheme dracula

" save when losing focus (may not work in terminal vim)
if has('autocmd') && (has('gui_running') || has('nvim'))
  au FocusLost * :silent! wa
endif

" case search
set ignorecase                  " ignore case for searching
set smartcase                   " but look for case if I search with it

" ensure xterm-256color
if &term =~ '256color'
  set t_Co=256
endif

" KEYS
if has('paste')
  set pastetoggle=<C-p>         " for vim paste toggle (nvim handles automatically)
endif
inoremap jk <Esc>               " use jk for esc while in insert mode
let mapleader = ","             " map leader to comma

nnoremap <F5> "=strftime("%Y-%m-%d_%X")<CR>P
inoremap <F5> <C-R>=strftime("%Y-%m-%d_%X")<CR>
iab <expr> sdate strftime("%Y-%m-%d_%X")

" ABBREVIATIONS
abbr _lia <li><a href=""></a></li>

" FUNCTIONS
" to insert md code block. need to setup keymap
function! s:CodeSnippet(...)
  let out = '```'
  if a:0 == 1
    let out = out . a:1
  endif
  "      ↓ makes it easier to %s OPENING set of code fences
  put = ' '.out
  "   ↓ outputs clipboard
  put +
  put ='```'
endfunction

" it's a .vimrc file that makes you look like a ninja. it's the absolute
" minimal setup. no colors, no highlights, no messages, no status bar,
" nothing. just text.

"ninja vimrc http://xero.nu
"set nocompatible
"set modelines=0
"set shortmess+=I
"set noshowmode
"set noshowcmd
"set hidden
"set lazyredraw
"set noruler
"set laststatus=0
"syntax off
"filetype off