import = ["/home/laydros/.config/alacritty/themes/dracula.toml"]

[bell]
animation = "EaseOutExpo"

[cursor]
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "Hack"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[scrolling]
history = 90000

[shell]
args = ["-l", "-c", "tmux"]
program = "/usr/bin/zsh"

[window]
dynamic_title = true

[window.dimensions]
columns = 110
lines = 38

[window.padding]
x = 4
y = 2
